# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for NPM
  - package-ecosystem: 'npm'
    directory: '/'
    directory: '/astro/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    reviewers:
      - 'vixshan'
    labels:
      - 'dependencies'
    ignore:
      #     - dependency-name: "discord.js"
      - dependency-name: 'pretty-ms'
      - dependency-name: 'node-fetch'

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "vixshan"
    labels:
      - "actions"